import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import react from "react"
import NavbarDemo from "@/components/Navbar";
import HeroSection from "@/components/HeroSection";
import Featuredcourses from "@/components/Featuredcourses";
import WhyChooseUs from "@/components/WhyChooseUs";
import InfiniteMove from "@/components/InfiniteMove";
import Footer from "@/components/Footer";
// import Instructors from "@/components/Instructors";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Music Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <>
      <NavbarDemo/>
      
      <HeroSection/>
      
      <Featuredcourses/>
      
      <WhyChooseUs/>
      {children}
      <InfiniteMove/>
     
      <Footer/>
   </>
      
   
     
  );
}
